#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>
#include <stdlib.h>

/* generated by fbt from .png files in images folder */
#include <dpad_keyboard_icons.h>

#include "menu.h"

typedef enum {
    EventTypeTick,
    EventTypeKey,
} EventType;

typedef struct {
    EventType type;
    InputEvent input;
} PluginEvent;

typedef struct {
    int menu;
    char *buffer;
    FuriMutex* mutex;
} PluginState;

static void render_callback(Canvas* const canvas, void* ctx) {
    PluginState* plugin_state = (PluginState*)ctx;
    furi_mutex_acquire(plugin_state->mutex, FuriWaitForever);
    if(plugin_state == NULL) {
        return;
    }

    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str_aligned(
        canvas, 0, 0, AlignLeft, AlignTop, plugin_state->buffer);

    DMenu *menu = menus[plugin_state->menu];

    canvas_draw_str_aligned(
        canvas, 40, 30, AlignLeft, AlignTop, menu->up.label);

    canvas_draw_str_aligned(
        canvas, 0, 40, AlignLeft, AlignTop, menu->left.label);

    canvas_draw_str_aligned(
        canvas, 65, 40, AlignLeft, AlignTop, menu->right.label);

    canvas_draw_str_aligned(
        canvas, 40, 50, AlignLeft, AlignTop, menu->down.label);

    furi_mutex_release(plugin_state->mutex);
}

static void input_callback(InputEvent* input_event, FuriMessageQueue* event_queue) {
    furi_assert(event_queue);

    PluginEvent event = {.type = EventTypeKey, .input = *input_event};
    furi_message_queue_put(event_queue, &event, FuriWaitForever);
}

static void dpad_keyboard_state_init(PluginState* const plugin_state) {
    plugin_state->menu = 0;
    plugin_state->buffer = (char*)malloc(100);
}

static void dpad_keyboard_apply_option(PluginState *plugin_state, DOption *option) {
    if (option->value) {
        size_t old_len = strlen(plugin_state->buffer);
        size_t option_len = strlen(&option->value);
        size_t new_len = old_len + option_len;
        plugin_state->buffer = realloc(plugin_state->buffer, new_len + 1);
        strncpy(plugin_state->buffer + old_len, &(option->value), option_len);
        plugin_state->buffer[new_len + 1] = 0;
    }
    plugin_state->menu = option->next_menu;
}

static void dpad_keyboard_backspace(PluginState *plugin_state) {
    size_t len = strlen(plugin_state->buffer);
    plugin_state->buffer[len - 1] = 0;
}

int32_t dpad_keyboard_app() {
    UNUSED(menus);
    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(PluginEvent));

    PluginState* plugin_state = malloc(sizeof(PluginState));

    dpad_keyboard_state_init(plugin_state);

    plugin_state->mutex = furi_mutex_alloc(FuriMutexTypeNormal);
    if(!plugin_state->mutex) {
        FURI_LOG_E("dpad_keyboard", "cannot create mutex\r\n");
        free(plugin_state);
        return 255;
    }

    // Set system callbacks
    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, render_callback, plugin_state);
    view_port_input_callback_set(view_port, input_callback, event_queue);

    // Open GUI and register view_port
    Gui* gui = furi_record_open("gui");
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    PluginEvent event;
    for(bool processing = true; processing;) {
        FuriStatus event_status = furi_message_queue_get(event_queue, &event, 100);

        furi_mutex_acquire(plugin_state->mutex, FuriWaitForever);

        if(event_status == FuriStatusOk) {
            // press events
            if(event.type == EventTypeKey) {
                if(event.input.type == InputTypePress) {
                    switch(event.input.key) {
                    case InputKeyUp:
                        dpad_keyboard_apply_option(plugin_state,
                                &(menus[plugin_state->menu]->up));
                        break;
                    case InputKeyDown:
                        dpad_keyboard_apply_option(plugin_state,
                                &(menus[plugin_state->menu]->down));
                        break;
                    case InputKeyRight:
                        dpad_keyboard_apply_option(plugin_state,
                                &(menus[plugin_state->menu]->right));
                        break;
                    case InputKeyLeft:
                        dpad_keyboard_apply_option(plugin_state,
                                &(menus[plugin_state->menu]->left));
                        break;
                    case InputKeyOk:
                    case InputKeyBack:
                        if (plugin_state->menu == MAIN_MENU) {
                            dpad_keyboard_backspace(plugin_state);
                        } else {
                            plugin_state->menu = MAIN_MENU;
                        }
                        break;
                    default:
                        break;
                    }
                } else if (event.input.type == InputTypeLong && event.input.key == InputKeyBack) {
                    processing = false;
                }
            }
        } else {
            FURI_LOG_D("dpad_keyboard", "FuriMessageQueue: event timeout");
        }

        view_port_update(view_port);
        furi_mutex_release(plugin_state->mutex);
    }

    view_port_enabled_set(view_port, false);
    gui_remove_view_port(gui, view_port);
    furi_record_close("gui");
    view_port_free(view_port);
    furi_message_queue_free(event_queue);
    furi_mutex_free(plugin_state->mutex);

    return 0;
}
